bookcase/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

#
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'readings:review_list'}, name='logout'),
    url(r'^reviews/', include('readings.urls',
                              namespace='readings',
                              app_name='readings')),

    url(r'^', include('readings.urls',
                      namespace='readings',
                      app_name='readings')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

readings/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /
    url(r'^authentication_error/(?P<error_type>\d)/$', views.auth_error_message, name='auth_error_message'),

    url(r'^$', views.index, name='index'),
    url(r'^review/reviews$', views.review_list, name='review_list'),
    url(r'^book/books$', views.book_list, name='book_list'),

    url(r'^review/(?P<review_id>\d+)/$', views.review_detail, name='review_detail'),
    url(r'^book/(?P<book_id>\d+)/$', views.book_detail, name='book_detail'),

    url(r'^review/new/$', views.review_new, name='review_new'),
    url(r'^book/new/$', views.book_new, name='book_new'),

    url(r'^review/(?P<pk>\d+)/edit/$', views.review_edit, name='review_edit'),
    url(r'^book/(?P<pk>\d+)/edit/$', views.book_edit, name='book_edit'),
    # url(r'^upload/$', views.model_form_upload, name='upload'),

    # url(r'^book$', views.book_list, name='book_list'),
    # url(r'^book/(?P<book_id>[0-9]+)/$', views.book_detail, name='book_detail'),
]

readings/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import URLValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

import datetime
import numpy as np

class Reader(models.Model):
    GENDER_CHOICES = (
        ('M', 'male'),
        ('F', 'female'),
        ('O', 'Other /not specified')
    )

    YEAR_CHOICES = []
    YEAR_CHOICES.append((1000,'1000'))

    for r in range(1890, (datetime.datetime.now().year + 1)):
        YEAR_CHOICES.append((r, r))
    # user_id=models.IntegerField(default=0)

    user = models.OneToOneField(User, on_delete=models.CASCADE,blank=True)
    gender = models.CharField(max_length=1,choices=GENDER_CHOICES,default='O')
    year_of_birth = models.IntegerField(choices=YEAR_CHOICES, default=1000)

    def __str__(self):  # __unicode__ for Python 2
        return self.user.username

    @receiver(post_save, sender=User)
    def create_or_update_user_profile(sender, instance, created, **kwargs):
        if created:
            Reader.objects.create(user=instance)
        instance.reader.save()


class Book(models.Model):
    added_by = models.ForeignKey(User, null=True, blank=True)
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    illustrator = models.CharField(max_length=50,blank=True)
    publisher = models.CharField(max_length=50,blank=True)
    year = models.IntegerField(default=0,blank=True)
    wiki_page = models.CharField(max_length=200, blank=True,  validators=[URLValidator()])
    number_of_pages = models.IntegerField(blank=True, default=0)
    adding_date = models.DateTimeField(auto_now_add=True)
    cover_image = models.ImageField(upload_to='cover_images',default='cover_images/cover.jpg')


    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)

    def __unicode__(self):
        return self.name
    objects = models.Manager() # the default manager (used for queries for example)


class Review(models.Model):
    RATING_CHOICES = (
        (1, 'did\'nt like it so much'),
        (2, 'thought it was OK'),
        (3, 'Loved it!'),
    )
    # id = models.IntegerField(unique=True, db_index=True, blank=True, primary_key=True, null=False,auto_created=True)
    book = models.ForeignKey(Book)
    reviewed_by = models.ForeignKey(User)
    published_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    body = models.TextField(blank=True)
    quote = models.CharField(max_length=200, blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES)

    def publish(self):
        self.published_date = timezone.now()
        self.save()


    def __unicode__(self):
        return self.book.name + ' by '+self.reviewed_by.username

    objects = models.Manager() # the default manager (used for queries for example)

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    # document = models.FileField(upload_to='documents/')
    cover_image = models.ImageField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

readings/forms.py
from django import forms
from .models import Review, Book
#from .models import Document


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        # fields = ('book','body','quote','rating','reviewed_by')
        fields = ('book','body','quote','rating') # reviewed by is added automatically



class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('name','author','illustrator','publisher','year','number_of_pages','wiki_page','cover_image')



# class DocumentForm(forms.ModelForm):
#     class Meta:
#         model = Document
#         fields = ('description', 'cover_image', )

readings/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .models import Review, Book
from .forms import ReviewForm, BookForm
# ,DocumentForm
from django.shortcuts import redirect

from django.contrib.auth import logout
from django.conf import settings
from django.core.files.storage import FileSystemStorage


from django.http import HttpResponse

from django.template.defaulttags import register


def index(request):
    books = Book.objects.filter(adding_date__lte=timezone.now()).order_by('-adding_date')
    books=books[0:min(len(books),3)]
    reviews = Review.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    reviews=reviews[0:min(len(reviews),3)]

    dict_review_rating_to_text(reviews)
    return render(request,
                  'readings/index.html',
                  {'reviews': reviews,
                   'books': books})

def dict_review_rating_to_text(reviews=[]):
    """ this function takes the list of reviews as input and return the text of the rating of these reviews"""
    text_rating={1: 'did\'nt like it so much',
                 2: 'thought it was OK',
                 3: 'Loved it!'}
    for i in range (0,len(reviews)):
        reviews[i].text_rating=text_rating[reviews[i].rating]
    return reviews

def review_list(request):
    # import pdb;
    # pdb.set_trace()
    reviews = Review.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    dict_review_rating_to_text(reviews)
    return render(request,
                  'readings/review_list.html',
                  {'reviews': reviews})

def book_list(request):
    # import pdb;
    # pdb.set_trace()
    books = Book.objects.filter(adding_date__lte=timezone.now()).order_by('-adding_date')
    # dict_review_rating_to_text(books)
    return render(request,
                  'readings/book_list.html',
                  {'books': books})




def review_detail(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    dict_review_rating_to_text([review]) # add a column with the rating text based on the dictionary above
    return render(request, 'readings/review_detail.html',
                  {'review': review})


def book_detail(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    reviews = Review.objects.filter(book=book_id).order_by('-published_date')
    dict_review_rating_to_text(reviews)

    # reviews = Review(review.book=book.id, tagline='All the latest Beatles news.')
    return render(request, 'readings/book_detail.html',
                  {'book': book,
                   'reviews': reviews})

def review_new(request):
    if not request.user.is_authenticated():
        return redirect('readings:auth_error_message', error_type=1)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            review = form.save(commit=False)
            review.reviewed_by = request.user
            review.published_date = timezone.now()
            review.save()
            id=review.pk
            return redirect('readings:review_detail', review_id=id)
    else:
        form = ReviewForm()
    return render(request, 'readings/review_edit.html', {'form': form})


def book_new(request):
    if not request.user.is_authenticated():
        return redirect('readings:auth_error_message', error_type=1)
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=False)
            book = form.save(commit=False)
            book.added_by = request.user
            book.adding_date = timezone.now()
            book.save()
            # book = form.save()
            id = book.pk
            return redirect('readings:book_detail',book_id=id)
    else:
        form = BookForm()
    return render(request, 'readings/book_edit.html', {'form': form})

def review_edit(request, pk):
    review = get_object_or_404(Review, pk=pk)

    if review.reviewed_by!=request.user:
        return redirect('readings:auth_error_message', error_type=0)

    if request.method == "POST":
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.updated_date = timezone.now()
            review.save()
            return redirect('readings:review_detail', review_id=review.pk)
    else:
        form = ReviewForm(instance=review)
    return render(request, 'readings/review_edit.html', {'form': form})

def book_edit(request, pk):
    book = get_object_or_404(Book, pk=pk)

    # if review.reviewed_by!=request.user:
    #     return redirect('readings:auth_error_message', error_type=0)

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            book.added_by = request.user
            book.updated_date = timezone.now()
            book.save()
            return redirect('readings:book_detail', book_id=book.pk)
    else:
        form = BookForm(instance=book)
    return render(request, 'readings/book_edit.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect('readings:review_list')

# def log_in(request):
#     logout(request)
#     return redirect('login')

def auth_error_message(request,error_type=0, message='',logged_in=''):
    error_type_get=request.get_full_path().rsplit('/',2)[-2] # get the last digit if the url (error-type)
    try: error_type_get =int(error_type_get)
    except: pass
    message = create_error_message(error_type=error_type_get)
    logged_in=request.user
    return render(request, 'readings/error_message.html',
                  {'message': message,
                   'logged_in':logged_in})


def create_error_message(error_type=0):
    if error_type == 0:
        message = "It looks as if you're trying to edit someone else's review. That's not nice ;)"
    elif error_type == 1:
        message = "You need to log-in before  registering your readings or books)"
    else: message = "Error No "+str(error_type)
    return message


# def model_form_upload(request):
#     if request.method == 'POST':
#         form = DocumentForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('readings:index')
#     else:
#         form = DocumentForm()
#     return render(request, 'readings/model_form_upload.html', {
#         'form': form
#     })

readings/templates/readings/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--for proper rendering and touch zooming-->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- compiled and minified CSS -->
    <link rel="stylesheet"
          href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!--fonts-->
    <link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet'  type='text/css'>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <!--<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">-->


    <link rel="stylesheet" href="{% static 'css/readings.css' %}">


    <title>Log-Book</title>
</head>

<body>
    <div class="page-header">
        <div class="container">
            <img class="img-responsive" src="{% static 'images/books_flat.jpg' %}" alt="My image" width="300" height="100" />
        </div>
    </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <!--<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="{% url 'readings:index' %}">
                    <span class="glyphicon glyphicon-home"></span>LogBook</a>
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                  <!--<li><a href="{% url 'readings:index' %}"><span class="glyphicon glyphicon-home"></span> Home </a></li>-->
                  <li><a href="{% url 'readings:review_list' %}"><span class="glyphicon glyphicon-text-background"></span> Readings </a></li>
                  <li><a href="{% url 'readings:book_list' %}"><span class="glyphicon glyphicon-book"></span> Books </a></li>
                  <li><a href="{% url 'readings:review_new' %}"> <span class="glyphicon glyphicon-plus"></span> Add a New Reading  </a></li>
                  <li><a href="{% url 'readings:book_new' %}" >  <span class="glyphicon glyphicon-plus"></span> Add a New Book</a></li>
                </ul>


                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li ><a><span class="glyphicon glyphicon-user"></span>
                            {{request.user.username}}</a></li>
                    <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>
                        Logout</a></li>
                    {% else %}
                    <li ><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>
                        Login</a></li>
                    {% endif %}
                </ul>


            </div>
        </div><!-- /.container-fluid -->
    </nav>

    <div class="content container">
        {% block title %}
        {% endblock %}

        <div class="sub-header">
            {% block sub_title%}
            {% endblock %}
        </div>

        <div class="row">
            <div class="col-md-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

<!--base-->

readings/templates/readings/book_detail.html
{% extends 'readings/base.html' %}
{% load staticfiles %}

{% block title%}
    <h1>
        {{ book.name }}
        <a class="btn btn-default" href="{% url 'readings:book_edit' pk=book.pk %}">
        <span class="glyphicon glyphicon-pencil"></span></a>
    </h1>
    <hr>
{% endblock %}

{% block sub_title %}
    <!--<h2 class="sub-title">latest reviews</h2>-->
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-7">
        <div class="well">
            <div class="row">
                <div class="col-sm-7">
                    <div class="review">
                    <!--<h3><a href="{% url 'readings:book_detail' book.id %}">{{ book.name }}</a></h3>-->
                    <h4>Wrriten by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.author }}</a></h4>
                    {% if  book.illustrator %}
                        <h4>Illustrated by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.illustrator }}</a></h4>
                    {% endif %}
                    {% if  book.publisher %}
                        <h4>Published by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.publisher }}</a></h4>
                    {% endif %}
                    {% ifnotequal  book.year 1  %}
                        <h4>first edition was publish in {{ book.year }} </h4>
                    {% endifnotequal %}

                    {% if  book.number_of_pages %}
                        <h4>{{ book.number_of_pages }} pages</h4>
                    {% endif %}

                    {% if  book.wiki_page %}
                    <h4><a href="{{ book.wiki_page }}"> {{book.name}} @ wikipedia.org</a>  </h4>
                    {% endif %}
                        <h4>Added by: <b> {{ book.added_by.username }} </b>  </h4>
                        <div class="date">
                            <p>added on: {{book.adding_date|date:"SHORT_DATE_FORMAT"}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="img-rounded" >
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{book.cover_image}}" alt="cover" />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <hr>
                </div>
            </div>
        </div>
    </div>
      <div class="col-sm-5">
        <div class="sub-header">
            <h2 class="sub-title">Read by</h2>
            <hr />
        </div>
          {% for review in reviews %}
          <div class="well">
              <div class="row">
                  <div class="col-sm-12">
                      <div class="review">
                    <!--<h3><a href="{% url 'readings:review_detail' review.id %}">{{ review.book.name }}</a></h3>-->
                          <h2>Read by: <b> {{ review.reviewed_by.username }} </b> <h3> who {{ review.text_rating }}</h3> </h2>
                          <div class="date">
                            <p>published on: {{review.published_date }}</p>
                          </div>
                          <p style = "color:blue"> <a href="{% url 'readings:review_detail' review.id %}">
                              {{ review.body|linebreaksbr|truncatechars:300 }}</a></p>
                      </div>
                  </div>
              </div>
          </div>
      {% endfor %}
    </div>




  </div>
</div>

{% endblock %}



    <!--<h1>-->
        <!--<a href="">{{ book.name }}</a>-->
    <!--</h1>-->

    <!--<h2 class="sub-title">Written by: {{book.author}} </h2>-->
    <!--{% if  book.illustrator %}-->
        <!--<h2 class="sub-title">Illustrated by: {{book.illustrator}} </h2>-->
    <!--{% endif %}-->

readings/templates/readings/book_edit.html
{% extends 'readings/base.html' %}

<!--<form action="" method="post" enctype="multipart/form-data">-->
{% block content %}
    <h1>Book details</h1>
    <form action=""  method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        {% if user.is_authenticated %}
            <button type="submit" class="save btn btn-default">Save</button>
        {% endif %}
    </form>
{% endblock %}

readings/templates/readings/book_list.html
{% extends 'readings/base.html' %}
{% load staticfiles %}

{% block title%}
    <h1> Books list  </h1>
    <hr>
{% endblock %}

{% block sub_title %}
    <!--<h2 class="sub-title">Latest readings </h2>-->
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6">
            <!--<div class="sub-header">-->
                <!--&lt;!&ndash;<hr />&ndash;&gt;-->
            <!--</div>-->
    {% for book in books %}
        <div class="well">
            <div class="row">
                <div class="col-sm-9">
                    <div class="review">
                        <h3><a href="{% url 'readings:book_detail' book.id %}">{{ book.name }}</a></h3>
                        <h4>Wrriten by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.author }}</a></h4>
                        {% if  book.illustrator %}
                            <h4>Illustrated by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.illustrator }}</a></h4>
                        {% endif %}

                        {% if  book.publisher %}
                            <h4>published by: <a href="{% url 'readings:book_detail' book.id %}">
                                {{ book.publisher }}</a></h4>
                        {% endif %}

                        <h4>added by: <b> {{ book.added_by.username }} </b>  </h4>
                        <div class="date">
                            <p>added on: {{book.adding_date}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="img-rounded" >
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{book.cover_image}}" alt="cover" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <hr>
                </div>
            </div>
        </div>
        {% endfor %}{% endblock %}
    </div>
  </div>
</div>

readings/templates/readings/error_message.html
{% extends 'readings/base.html' %}

{% block title%}

{% endblock %}


{% block sub_title %}

    <h2 class="error_message">
        Hi  {{request.user.first_name}}, {{ message }}
    </h2>

    <h4>

        (You're logged in as '{{ logged_in }}')
    </h4>
{% endblock %}

readings/templates/readings/index.html
{% extends 'readings/base.html' %}
{% load staticfiles %}

{% block title%}
    <h1> Log  Book </h1>
    <hr>
{% endblock %}


{% block sub_title %}
    <!--<h2 class="sub-title">latest reviews</h2>-->
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6">
        <div class="sub-header">
            <!--<hr />-->
            <h2 class="sub-title">Latest reviews</h2>
            <hr />
        </div>
      {% for review in reviews %}
        <div class="well">
            <div class="row">
                <div class="col-sm-9">
                    <div class="review">
                        <h3><a href="{% url 'readings:book_detail' review.book.id %}">{{ review.book.name }}</a></h3>
                        <h4>Read by: <b> {{ review.reviewed_by.username }} </b> who {{ review.text_rating }} </h4>
                        <h4>Wrriten by: <a href="{% url 'readings:review_detail' review.id %}">{{ review.book.author }}</a></h4>
                        {% if  review.book.illustrator %}
                            <h4>Illustrated by: <a href="{% url 'readings:review_detail' review.id %}">{{ review.book.illustrator }}</a></h4>
                        {% endif %}
                        <div class="date">
                            <p>published on: {{review.published_date }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="img-rounded" >
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{review.book.cover_image}}" alt="cover"/>


                    </div>
                </div>
            <!--width="300" height="100"-->
            </div>
            <div class="row">
                <div class="col-sm-12">
                  <p style = "color:blue"> <a href="{% url 'readings:review_detail' review.id %}">
                                  {{ review.body|linebreaksbr|truncatechars:300 }}</a></p>
                  <hr>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>



    <div class="col-sm-6">
        <div class="sub-header">
            <!--<hr />-->
            <h2 class="sub-title">Latest Books</h2>
            <hr />
        </div>
        {% for book in books %}
        <div class="well">
            <div class="row">
                <div class="col-sm-9">
                    <div class="review">
                    <h3><a href="{% url 'readings:book_detail' book.id %}">{{ book.name }}</a></h3>
                    <h4>Wrriten by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.author }}</a></h4>
                    {% if  book.illustrator %}
                        <h4>Illustrated by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.illustrator }}</a></h4>
                    {% else %}
                        <!--<br>-->
                    {% endif %}

                    {% if  book.publisher %}
                        <h4>Published by: <a href="{% url 'readings:book_detail' book.id %}">{{ book.publisher }}</a></h4>
                    {% else %}
                        <!--<br>-->
                    {% endif %}
                    <h4>Added by: <b> {{ book.added_by.username }} </b>  </h4>
                    <div class="date">
                        <p>added on: {{book.adding_date}}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="img-rounded" >
                    <img class="img-responsive" src="{{ MEDIA_URL }}{{book.cover_image}}" alt="cover" />
                </div>
            </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
              <hr>
          </div>
        </div>
        </div>
        {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

readings/templates/readings/model_form_upload.html
{% extends 'readings/base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'readings:index' %}">Return to home</a></p>
{% endblock %}

readings/templates/readings/review_detail.html
{% extends 'readings/base.html' %}
{% load staticfiles %}

{% block title%}
<h1>
    <a href="{% url 'readings:book_detail' review.book.id %}">{{ review.book.name }}</a>
</h1>
<h3><a href="{% url 'readings:book_detail' review.book.id %}">  {{ review.book.author}}</a>
    {% if review.book.number_of_pages %}
        <small>,  {{review.book.number_of_pages }} pages</small>
    {% endif %}
    <a class="btn btn-default" href="{% url 'readings:review_edit' pk=review.pk %}">
    <span class="glyphicon glyphicon-pencil"></span></a>
</h3>
<hr>

{% endblock %}


{% block sub_title %}
<!--<div id="sub_title" >-->
    <!--<h2 class="sub-title">read by: <i>{{review.reviewed_by.username}}</i> who </h2>-->
    <!--<h3>  {{ review.text_rating|linebreaksbr }} </h3>-->
<!--</div>-->
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-10">
        <div class="well">
            <div class="row">
                <div class="col-sm-9">
                    <div class="review">
                        <div>
                            <h2 style="display: inline">read by: <i>{{review.reviewed_by.username}}</i>  </h2>
                            <h3 style="display: inline ; color: darkslategrey">who  {{ review.text_rating }} </h3>
                        </div>
                        {% if review.published_date %}
                        <br>

                        <div class="date">
                            Submitted on {{ review.published_date }}
                        </div>
                        <div class="date">
                            Last updated on {{ review.updated_date }}
                        </div>
                        {% endif %}
                        <hr>
                        <p style="color: midnightblue">{{ review.body|linebreaksbr }}</p>

                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="img-rounded" >
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{review.book.cover_image}}" alt="cover" />
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>

        <!--<br>-->
        <p>-------------------------</p>
        <!--<h1>{{ review.book.name }}</h1>-->

        <br>

    </div>
{% endblock %}

readings/templates/readings/review_edit.html
{% extends 'readings/base.html' %}


{% block content %}
    <h1>Update Reading</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        {% if user.is_authenticated %}
            <button type="submit" class="save btn btn-default">Save</button>
        {% endif %}
        <br>
        <br>

        <p>------------------ </p>
    </form>
{% endblock %}